# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [9]:
import numpy as np

A = np.arange(1, 16).reshape(3,5)

print(A)
print("dimension (number of axes): ", A.ndim)
print("shape: ", A.shape)
print("size: ", A.size)
print("datatype of matrix A: ", A.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
dimension (number of axes):  2
shape:  (3, 5)
size:  15
datatype of matrix A:  int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [40]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print()

# Elementwise subtraction.
A = B - C
print(A)
print()

# Elementwise multiplication.
A = B * C
print(A)
print()


# Matrix multiplication (by default you should use the @ operator).
A = B @ C
print(A)





[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [68]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

print("\nExponentiate each number elementwise:")
print(np.exp(B))

print("\nCalculate the minimum value in the whole matrix:")
print(B.min())

print("\nCalculcate the minimum value in each row:")
print(B.min(axis=1))

print("\nCalculcate the minimum value in each column:")
print(B.min(axis=0))

print("\nFind the index value for the minimum value in the whole matrix (hint: use np.argmin):")
print(np.argmin(B))

print("\nFind the index value for the minimum value in each row (hint: use np.argmin):")
print(np.argmin(B, axis=1))

print("\nCalculate the sum for all elements:")
print(B.sum())

print("\nCalculate the mean for each column:")
print(B.mean(axis=0))

print("\nCalculate the median for each column:")
print(np.median(B, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiate each number elementwise:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Calculate the minimum value in the whole matrix:
1

Calculcate the minimum value in each row:
[1 4 7]

Calculcate the minimum value in each column:
[1 2 3]

Find the index value for the minimum value in the whole matrix (hint: use np.argmin):
0

Find the index value for the minimum value in each row (hint: use np.argmin):
[0 0 0]

Calculate the sum for all elements:
45

Calculate the mean for each column:
[4. 5. 6.]

Calculate the median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [72]:
print(A)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [86]:
A[1]
print(A[1])
print(A[1,...])
print(A[1,:])

[30. 30. 30.]
[30. 30. 30.]
[30. 30. 30.]


**Answer:**

In [ ]:
# select all elements for the missing axes, in our case this is the entire row with index 1

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [88]:
for i in A:
    print(i)

[12. 12. 12.]
[30. 30. 30.]
[48. 48. 48.]


In [90]:
for element in A.flat:
    print(element)

12.0
12.0
12.0
30.0
30.0
30.0
48.0
48.0
48.0


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [92]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# 1. Koden skapar en 1D-array a med 30 element 
# 2. Omformar a till en 3D-array b med 2 block, varje med 3 rader och beräknar automatiskt antalet kolumner (30 element / (2 * 3) = 5) 
# 3. Tre axlar betyder att arrayen har tre nivåer: 2 block, varje med 3 rader och 5 kolumner.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [94]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [96]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [100]:
A = np.arange(1, 5).reshape(2,2)
print(A)
print()

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]

[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [134]:
import numpy as np

def add_mult_matrices(matrix_1, matrix_2, operation):
    """
    Addition or multiplication of two matrices according to the rules of matrix algebra.
    """

    # Checks
    if not isinstance(matrix_1, np.ndarray) or not isinstance(matrix_2, np.ndarray):
        raise TypeError("Both inputs must be of type numpy.ndarray.")    
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'.")
    
    if operation == 'add':
        if matrix_1.shape != matrix_2.shape:
            raise ValueError("For addition, matrices must have the same shape.")
        return matrix_1 + matrix_2    
    elif operation == 'multiply':
        if matrix_1.shape[1] != matrix_2.shape[0]:
            raise ValueError("For multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix.")
        return matrix_1 @ matrix_2


matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix 1:")
print(matrix1)

matrix2 = np.array([[7, 8, 9], [10, 11, 12]])
print("Matrix 2:")
print(matrix2)

try:
    result_add = add_mult_matrices(matrix1, matrix2, 'add')
    print("Result of addition matrix1 + matrix2 = ")
    print(result_add)

    matrix3 = matrix2.reshape(matrix1.shape[1],matrix2.shape[0])
    print("Matrix 3:")
    print(matrix3)
    result_mult = add_mult_matrices(matrix1, matrix3, 'multiply')
    print("Result of multiplication matrix1 + matrix3 = ")
    print(result_mult)    
except Exception as e:
    print(f"Error: {e}")


Matrix 1:
[[1 2 3]
 [4 5 6]]
Matrix 2:
[[ 7  8  9]
 [10 11 12]]
Result of addition matrix1 + matrix2 = 
[[ 8 10 12]
 [14 16 18]]
Matrix 3:
[[ 7  8]
 [ 9 10]
 [11 12]]
Result of multiplication matrix1 + matrix3 = 
[[ 58  64]
 [139 154]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [ ]:
# Uppgift 10.1.1.

In [3]:
import numpy as np
x = np.array([4, 3]) 
print(x)

[4 3]


In [ ]:
# a) x = (4,3) Radvektorn x har dimensionen 1×2 eftersom den har en rad och två kolumner. Den är en tvådimensionell vektor.

In [5]:
print(f"Dimensionen av vektorn x: {x.shape}")

Dimensionen av vektorn x: (2,)


In [ ]:
# b) 5x = (20,15)

In [9]:
print(5 * x)

[20 15]


In [ ]:
# c) 3x = (12,9)

In [11]:
print(3 * x)

[12  9]


In [ ]:
# d) 5x + 3x = (5 + 3)x = 8x = (32,24)

In [13]:
print((5*x) + (3*x))

[32 24]


In [ ]:
# e) 8x = (32,24)

In [15]:
print(8 * x)

[32 24]


In [ ]:
# f) 4x − x = 3x = (12,9)

In [17]:
print(4*x - x)

[12  9]


In [ ]:
# g) [[4],
#     [3]]
# Kolumnvektorn x har dimensionen 2 × 1 eftersom den har två råder och en kolumn. Den är en tvådimensionell vektor. 

In [19]:
print(x.reshape(-1, 1))

[[4]
 [3]]


In [ ]:
# h) Nej, additionen det   är inte definierad eftersom är en radvektor och en annat är en kolumnvektor (2×1). 
#    Matematisk addition kräver att dimensionerna matchar.

In [ ]:
# i) ∥x∥ = 5

In [21]:
x_norm = np.linalg.norm(x)
print(f"||x|| = {x_norm}")

||x|| = 5.0


In [ ]:
# Uppgift 10.1.2.

In [161]:
import numpy as np
v = np.array([[3], [7], [0], [11]]) 
print(v)

[[ 3]
 [ 7]
 [ 0]
 [11]]


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [25]:
import numpy as np
v = np.array([[3], [7], [0], [11]]) 
print(v)

[[ 3]
 [ 7]
 [ 0]
 [11]]


In [27]:
# a) Dimensionen är (4x1), det är en kolumnvektor med 4 element.
print(f"Dimensionen av vektorn v: {v.shape}")

Dimensionen av vektorn v: (4, 1)


In [29]:
# b) 2v = [[ 6], [ 14], [ 0], [22]]
print(f"2v = {2 * v}")

2v = [[ 6]
 [14]
 [ 0]
 [22]]


In [31]:
# c) 5v + 2v = 7v = [[ 21], [ 49], [ 0], [77]]
print(f"2v = {5 * v + 2 * v}")

2v = [[21]
 [49]
 [ 0]
 [77]]


In [33]:
# d) 4v − 2v = 2v = [[ 6], [ 14], [ 0], [22]]
print(f"2v = {4 * v - 2 * v}")

2v = [[ 6]
 [14]
 [ 0]
 [22]]


In [35]:
# e) transponerad v = (3, 7, 0, 11) rådvektorn med den nya dimension (1x4)
v_transposed = v.reshape(-1, 1)
print(f"v transponerad:\n{v_transposed}")
print(f"Ny dimension: {v_transposed.shape}")

v transponerad:
[[ 3]
 [ 7]
 [ 0]
 [11]]
Ny dimension: (4, 1)


In [37]:
# f) ∥v∥ = 13.37908816025965
v_norm = np.linalg.norm(v)
print(f"||v|| = {v_norm}")

||v|| = 13.379088160259652


In [ ]:
# Uppgift 10.1.2.

In [41]:
import numpy as np
v1 = np.array([4, 3, 1, 5]) 
v2 = np.array([2, 3, 1, 1])
print(v1) 
print(v2) 

[4 3 1 5]
[2 3 1 1]


In [43]:
# a) ∥v1∥ = 7.14142842854285
v1_norm = np.linalg.norm(v1)
print(f"||v1|| = {v1_norm}")

||v1|| = 7.14142842854285


In [47]:
# b) ∥v1 − v2∥ 
v2_norm = np.linalg.norm(v2)
print(f"||v1|| = {v1_norm}")
print(f"||v2|| = {v2_norm}")
print(f"||v1||  = {v1_norm - v2_norm}")

||v1|| = 7.14142842854285
||v2|| = 3.872983346207417
||v1||  = 3.2684450823354334


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [4]:
import numpy as np
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [6]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [8]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
The base attribute of a view returns the original array while it returns None for a copy.
v1 is copy
v2 is view of array v1
when the array v1 changes, its view v2 also changes